FROM alpine:3.4

# Install kubectl
# Note: Latest version may be found on:
# https://aur.archlinux.org/packages/kubectl-bin/
ADD https://storage.googleapis.com/kubernetes-release/release/v1.5.3/bin/linux/amd64/kubectl /usr/local/bin/kubectl

ENV HOME=/config

RUN set -x && \
    apk add --no-cache curl ca-certificates && \
    chmod +x /usr/local/bin/kubectl && \
    \
    # Create non-root user (with a randomly chosen UID/GUI).
    adduser kubectl -Du 2342 -h /config && \
    \
    # Basic check it works.
    kubectl version --client

# Copy entrypoint.sh
COPY entrypoint.sh /config/entrypoint.sh

# Set permissions on the file.
RUN chown kubectl: /config/entrypoint.sh && \
    chmod +x /config/entrypoint.sh

USER kubectl

CMD ["/config/entrypoint.sh"]
