apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: spot-termination-notice-handler
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: spot-termination-notice-handler
      name: spot-termination-notice-handler
    spec:
      containers:
      - image: mumoshu/kube-spot-termination-notice-handler:1.3.3-0.9.0
        imagePullPolicy: IfNotPresent
        name: spot-termination-notice-handler
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
